### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [Luca96/lua-table#1]
Hello @Luca96 , I am graphic designer. I like to contribute to open source software. So i designed a logo for lua-table. I combined a tablo and the lua logo. If there is your another idea, feel free to say me. What do you think about this logo?

![luatable](https://user-images.githubusercontent.com/36298335/42813047-4141eede-89c8-11e8-87e9-688188c02cf1.jpg)

**Comment by Luca96** [comment]
Hi, great artworks! 
The first two are my favourite, so let me know what can i do to credit your work. Thanks.

**Comment by reallinfo** [comment]
You're welcome, I am glad you like it. Then I sent you a pr. All files (editablefile, png , svg)

Also, you can tell your friends that I designed a free logo.  So, if they have their needs, I can design a logo. Thanks! 

https://github.com/Luca96/lua-table/pull/2

**Comment by Luca96** [comment]
Thank you, i'll tell them about your work :)
